gcarreno/1brc-ObjectPascal

generator/Lazarus/src/generator.lpr
million (usa) = 1.000.000
million (de) = 1,000,000
billion (usa): 1.000.000.000
billion  (de):  1,000,000,000
=> locale format

generator/Common/generate.common.pas
https://forum.lazarus.freepascal.org/index.php/topic,66465.msg509571.html#msg509571
=> changes based on @PascalVault code

generator/Common/generate.common.pas, generator/Common/generate.console.pas, generator/Common/version.inc, generator/Delphi/generator.dpr, generator/Delphi/generator.dproj, generator/Lazarus/src/generator.lpr
Added the delphi console version of generator that should work with linux64. Was able to successfuly test windows version of the code and it works
=> Ported project to delphi

generator/Common/generate.common.pas
the previous version gave identical results only in the same processor "session"
=> improvement of the rng function

generator/Common/generate.common.pas
in order to make the data more realistic; the previous version generated min -99.9 and max 99.9 almost everywhere
=> added temperature range and offset for each station

entries/ikelaiah/LICENSE.md, entries/ikelaiah/README.md, entries/ikelaiah/src/OneBRC.lpi, entries/ikelaiah/src/OneBRC.lpr, entries/ikelaiah/src/stopwatch.pas, entries/ikelaiah/src/weatherstation.pas
This is ikelaiah's entry to the 1 BRC. 
First revision. Sequential approch.
The 1 billion row for testing has the same `sha256sum` as per requirement; `ebad17b266ee9f5cb3d118531f197e6f68c9ab988abc5cb9506e6257e1a52ce6 `.
The first 10 row also matched the baseline requirement as [stated in the Discord](https://discord.com/channels/570025060312547359/896807098518732901/1217616456007815228).
Credits has been added to acknowledge contributions from others.
My knowledge limitation in Free Pascal and concurrency at the moment.
Hoping to learn how to use concurrency before May 2024 for a better `time`.
=> ikelaiah's entry to the 1 BRC. New - Initial commit.

generator/Common/generate.common.pas, generator/Common/version.inc, generator/Delphi/src/generator.dpr, generator/Delphi/src/generator.dproj
eliminated compiler hints and warnings; set version to 1.1
generated 1BR file in Windows has exact hash match
=> polished up Delphi generator; hash verified

entries/rlawson/README.md, entries/rlawson/src/parser.pas, entries/rlawson/src/weather.lpi, entries/rlawson/src/weather.lpr
=> initial checkin

baseline/Lazarus/src/baseline.lpi, entries/ikelaiah/README.md, entries/ikelaiah/src/OneBRC.lpr, entries/ikelaiah/src/stopwatch.pas, entries/ikelaiah/src/weatherstation.pas
Hi @gcarreno ,
I've applied the rounding as shown in the [1brc-ObjectPascal](https://github.com/gcarreno/1brc-ObjectPascal)'s README.md.
Many thanks.
-ikelaiah
=> Ikelaiah Revision 02

entries/ikelaiah/README.md, entries/ikelaiah/src/OneBRC.lpr, entries/ikelaiah/src/weatherstation.pas
Hi @gcarreno ,
Another revision from me. 
This one is approx. 3-4 mins faster, and still single threaded.
Updated the `README.md` too.
Many thanks.
Regards,
Iwan
=> Update - Rev 3, 3-4 mins faster.

.gitignore, entries/dcornelius/README.md, entries/dcornelius/src/dcornelius.dpr, entries/dcornelius/src/dcornelius.dproj, entries/dcornelius/src/uChallengeCommon.pas, entries/dcornelius/src/uChallengeWithDictionary.pas, entries/dcornelius/src/uChallengeWithStringList.pas, entries/dcornelius/src/udmChallengeWithFireDAC.dfm, entries/dcornelius/src/udmChallengeWithFireDAC.pas
I'm not hoping to be anywhere close to the best time but I learned a lot and had fun!
=> Challenge Entry

entries/abouchez/README.md, entries/abouchez/src/brcmormot.lpr
I have refreshed the README file with the new algorithm, and its results.
By default, will propose to use all available cores, since it seems to be what achieves the best performance.
=> abouchez / mormot: updated README

entries/abouchez/README.md, entries/abouchez/src/brcmormot.lpr
enhanced README + sort function refactoring (no performance impact expected)
=> abouchez / mormot: refactoring/polishing

entries/bfire/src/ConsoleUnit.pas, entries/bfire/src/ProcessUnit.pas, entries/bfire/src/bfire.dpr, entries/bfire/src/bfire.dproj
Program should now ignore "-" in command line filename parameter. Program should not create file named: "CONSOLE". Note compiler warning still occurs.
=> Fix "-" issue

entries/ikelaiah/README.md, entries/ikelaiah/src/OneBRC.lpi, entries/ikelaiah/src/OneBRC.lpr, entries/ikelaiah/src/weatherstation.pas
Hi @gcarreno , 
This is my revision 4. About 2-3 mins faster on my laptop.
Thank you.
Regards,
Iwan
=> Update - Revision 04, 2-3 mins faster than the previous one.

entries/bfire/README.md, entries/bfire/src/ProcessUnit.pas, entries/bfire/src/bfire.dproj, entries/bfire/src/version.inc
Modify rounding to new baseline
=> Version 1.1

entries/abouchez/README.md
Added some reference links and material about high-performance programming on modern hardware, in our README.md file.
=> abouchez / mormot: enhanced README

entries/abouchez/src/brcmormot.lpr, spelunking/roundex/Common/roundex.common.pas
=> abouchez/mormot: disable SSE2 code to see if it is actually faster

entries/bfire/src/ProcessByHashUnit.pas, entries/bfire/src/bfire.dpr, entries/bfire/src/bfire.dproj
Use stream instead of old file references.  Minor cleanup.
=> Switch to TFileStream

entries/abouchez/README.md, entries/abouchez/src/brcmormot.lpr
It seems to be a good idea to share the hash table between threads.
=> abouchez/mormot: performance enhancements

entries/ikelaiah/README.md, entries/ikelaiah/src/weatherstation.pas
Hi @gcarreno ,
My latest revision for the 1BRC, version 7.
* Revision release - Sequential approach. 4-6 mins on my Inspiron 15 7510 laptop (a little improvement on speed).
* Converting Float as String to Int was a bit slow, so resorted to a lookup instead. This saves 30-45 seconds.
* Re-arranged `if` statements in two places. This saves 10-15 seconds x 2 = ~ 30 seconds saving.
The sha256 is `4256d19d3e134d79cc6f160d428a1d859ce961167bd01ca528daca8705163910` 
Thank you!
Regards,
Iwan Kelaiah
=> Ikelaiah rev07

entries/ikelaiah/README.md, entries/ikelaiah/src/weatherstation.pas
Hi @gcarreno ,
This is revision no 8.
* 1.8
* Revision release - Sequential approach. 3-5 mins on my Inspiron 15 7510 laptop, around 3m50s (a little improvement on speed).
* Removed double lookup on dictionaries; removed `.Contains` and used `TryGetValue` instead. This saves approx 60 seconds.
The SHA is `4256d19d3e134d79cc6f160d428a1d859ce961167bd01ca528daca8705163910`.
Many thanks,
Iwan
=> Ikelaiah rev08

entries/bfire/README.md, entries/bfire/src/ProcessByHashUnit.pas, entries/bfire/src/bfire.dpr, entries/bfire/src/version.inc
=> Version 2.1

entries/ikelaiah/README.md, entries/ikelaiah/src/weatherstation.pas
Hi @gcarreno ,
This is my revision no 9.
* 1.9
* Revision release - Sequential approach. 3-5 mins on my Inspiron 15 7510 laptop; around 3m8s (a little improvement on speed).
* Use `ShortString` whenever possible. This saves approx 20 seconds.
* Pre-allocate initial size for dictionaries. saves approx 20 seconds.
Many thanks.
-Iwan
=> Update - Rev 09.

entries/bfire/README.md, entries/bfire/src/ProcessByHashUnit.pas, entries/bfire/src/version.inc
=> Version 2.2

entries/abouchez/src/brcmormotfullcheck.lpi, entries/abouchez/src/brcmormotfullcheck.lpr, entries/abouchez/src/brcmormotold.lpi, entries/abouchez/src/brcmormotold.lpr, entries/abouchez/src/brcmormotpertheadht.lpi, entries/abouchez/src/brcmormotpertheadht.lpr, entries/abouchez/src/brcmormotsharedht.lpi, entries/abouchez/src/brcmormotsharedht.lpr
- good weekend of applying ideas ;)
- the main brcmormot.lpr program should be the fastest, with the `-f` command line option to run in "full name scan" mode, which is required for the original 1BRC challenge
- new brcmormotfullcheck and brcmormotperthreadht versions, which may be interesting running on the end hardware 
- the README file still to be updated
=> abouchez/mormot: some new versions

entries/hgrosser/README.md, entries/hgrosser/src/1brc.pas
The hash-list was optimized again and some other minor improvements made.
There is now a new Conditional "noCR" neccessary, IF the input file has no CR's (only LF's).
=> hgrosser: hash-list optimized, minor improvements

README.md, entries/abouchez/src/brcmormot.lpr, entries/abouchez/src/brcmormotfullcheck.lpr, entries/abouchez/src/brcmormotold.lpr, entries/abouchez/src/brcmormotpertheadht.lpr, entries/abouchez/src/brcmormotsharedht.lpr
=> abouchez/mormot: let all entries only support single LF

generator/Lazarus/src/generator.lpr
https://github.com/gcarreno/1brc-ObjectPascal/pull/120#issuecomment-2075016042
=> fixed error with `-4` option, reported by Georges Hatem

entries/ikelaiah/README.md, entries/ikelaiah/src/weatherstation.pas
Hi @gcarreno 
Here is another revision from me. 
* 1.10
* Revision release - Sequential approach. 3-5 mins on my Inspiron 15 7510 laptop, around 2m55s (a little improvement on speed).
* Reduced buffer for `TStreamReader` to `65536 * 2`. This saves approx 5 seconds.
* Changed hashmap from `TGHashMapLP` (linear probing) to `TGHashMapQP` (quadratic probing). This saves approx 5 seconds.
Thank you!
-Iwan
=> Ikelaiah rev10

entries/bfire/src/MultiThreadUnit.pas
=> Windowless

entries/hgrosser/README.md, entries/hgrosser/src/1brc_th.lpi, entries/hgrosser/src/1brc_th.pas
This is my very first program (!) I ever did with threads. Please see README.md for optimizing command line parameters. Thank you.
=> hgrosser: first version with threads

entries/bfire/README.md, entries/bfire/src/MultiThreadUnit.pas, entries/bfire/src/version.inc
Use a safer locking strategy for threads
=> Version 3.1

entries/abouchez/README.md
include latest numbers for @paweld
=> abouchez/mormot: updated README

entries/ikelaiah/README.md, entries/ikelaiah/src/weatherstation.pas
Hi @gcarreno ,
Here is my latest update.
- **1 thread**. Keeping it simple for now. 
- **No external deps**. No longer using LGenerics and it cannot compile against FPC trunk. The author is a bit busy with other commitments.
- **No memory map**. I couldn't find a cross platform lib to make this happen.
* Revision release - Sequential approach. 2-5 mins on my Inspiron 15 7510 laptop, around 2m40s (small improvement on speed).
* Called `TStreamReader.ReadLn`, twice in the `while..do` loop. This saves approx 5-10 seconds.
* Updated the Acknowledgments section. Added Benibela.
Thanks,
Iwan
=> Ikelaiah rev12

entries/benibela/README, entries/benibela/src/brows.lpi, entries/benibela/src/brows.lpr, entries/benibela/src/fasthashmap.pas, entries/benibela/src/mmaputils.pas
=> add entry benibela

entries/bfire/README.md, entries/bfire/src/ConsoleUnit.pas, entries/bfire/src/MultiThreadUnit.pas, entries/bfire/src/bfire.dpr, entries/bfire/src/version.inc
Option to use 1, 2 or 3 threads to read
=> Version 3.3

entries/bfire/README.md, entries/bfire/src/ConsoleUnit.pas, entries/bfire/src/MultiThreadUnit.pas, entries/bfire/src/bfire.dpr, entries/bfire/src/version.inc
Add command line parameter to turn off tabulation for testing only read speed
=> Version 3.4
